name: App-Consumer-Docker-Build-Push

env:  
  ContainerRegistryName: acr${{ vars.NAME}}${{ vars.SUFFIX}}.azurecr.io        
  ImageName: consumer-app
  ImageTag: 1.0.0.${GITHUB_RUN_NUMBER}
  DockerfilePath: cmd/consumer/dockerfile

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-package:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Login Container Registry
      run: |
          az acr login --name ${{ env.ContainerRegistryName }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |          
          docker build . --file ${{ env.DockerfilePath }} --tag "${{ env.ContainerRegistryName }}/${{ env.ImageName }}:${{ env.ImageTag }}"
      
    - name: Push the Docker image
      run: |          
          docker push "${{ env.ContainerRegistryName }}/${{ env.ImageName }}:${{ env.ImageTag }}"
